删除 awaitable_detached<> 类。减少代码重复
avplayer/ucoro pull request #40
Opened 2024-10-18 06:17 UTC by microcai

awaitable_detached 自从支持自身被 co_await 后，代码变得越来越像 awaitable<T>
相似度极高。

既然如此，不如合并代码。 detach 的时候，创建一个新的 awaitable<>。

有没有 detach 其实根本原因在于有没有被 co_await.

因此，在 析构函数里，判断是不是 done() 即可知道有没有被 co_await 过了。
如果没有被 co_await 过，则是 detach 模式。在析构里把协程给 resume 起来。

由于析构的时候没有进行 destroy 操作，因此需要在 final_awaiter 里进行清理。
现在 final_awaiter<T> 的部分清理逻辑本身就是从
awaitable_detached::promise_type::final_awaiter 里合并进来的。

同时detach 模式使用 awaitable<T> 后，也修正了 detach 模式下吞异常的问题。

2024-10-18 15:37 UTC, EvinceMoi commented
少了这么多代码

2024-10-18 15:39 UTC, microcai commented
是的

2024-10-18 15:42 UTC, EvinceMoi commented on include/ucoro/awaitable.hpp
> +		 	: current_coro_handle_(h)
这里混用了空格和tab

2024-10-18 15:57 UTC, EvinceMoi commented on include/ucoro/awaitable.hpp
> +				auto& calee_promise = current_coro_handle_.promise();
这里应该是callee，错别字

2024-10-18 16:07 UTC, EvinceMoi approved these changes
除了格式和错别字，我看没别的问题

2024-10-18 16:09 UTC, EvinceMoi requested changes
格式和错别字

2024-10-18 17:49 UTC, microcai reviewed
> 这里应该是callee，错别字 

是哦！

2024-10-18 17:53 UTC, microcai reviewed
已更新了。

2024-10-19 05:04 UTC, EvinceMoi approved these changes

2024-10-19 05:04 UTC, merged